// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PostDraft.Infrastructure.Context;

#nullable disable

namespace PostDraft.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class PostDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PostDraft.Domain.Entities.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "linkedIn",
                            CreatedAt = new DateTime(2025, 8, 25, 12, 51, 51, 915, DateTimeKind.Utc).AddTicks(4767),
                            Description = "Description",
                            Link = "https://www.linkedin.com/u/TaofeekAbdulazeez",
                            Title = "How to optimize linkedIn profile",
                            UpdatedAt = new DateTime(2025, 8, 25, 12, 51, 51, 915, DateTimeKind.Utc).AddTicks(5176)
                        },
                        new
                        {
                            Id = 2,
                            Category = "youtube",
                            CreatedAt = new DateTime(2025, 8, 25, 12, 51, 51, 915, DateTimeKind.Utc).AddTicks(6368),
                            Description = "Description",
                            Link = "https://youtube.com/TaofeekAbdulazeez",
                            Title = "How to monetize your skills",
                            UpdatedAt = new DateTime(2025, 8, 25, 12, 51, 51, 915, DateTimeKind.Utc).AddTicks(6369)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
